name: SAST

on: [push]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: RUN SAST
        uses: explyt/sast-action@main
        with:
          projectRoot: ${{github.workspace}}

